### ISSUE TITLE
Ingress IP in .env notation wrong

### ISSUE THREAD

**Issue by wolfganghuse** [jesse-gonzalez/nai-llm-fleet-infra#3]
.env tells me to add /32 to my ingress ip but code will also add this, resulting in double /32/32 in cluster-config.

**Comment by wolfganghuse** [comment]
same for istio ip

**Comment by jesse-gonzalez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Latest Issues found in Repo](https://trello.com/c/jFBT1fOI/117-fix-latest-issues-found-in-repo)
