### ISSUE TITLE
milvus bucket config missing in mgmt cluster profile

### ISSUE THREAD

**Issue by wolfganghuse** [jesse-gonzalez/nai-llm-fleet-infra#4]
Milvus Helm Chart is configured with general S3/Objects values but bucket is <nil>

**Comment by jesse-gonzalez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Latest Issues found in Repo](https://trello.com/c/jFBT1fOI/117-fix-latest-issues-found-in-repo)
