### ISSUE TITLE
Route53 / LE not working

### ISSUE THREAD

**Issue by wolfganghuse** [jesse-gonzalez/nai-llm-fleet-infra#5]
`│  > logger="cert-manager.challenges" key="uptrace/uptrace-grpc-tls-1-2309811006-3743117844"                                           │
│ E0419 11:18:31.339094       1 controller.go:167] "re-queuing item due to error processing" err=<                                     │
│     failed to determine Route 53 hosted zone ID: NoCredentialProviders: no valid providers in chain. Deprecated.                     │
│         For verbose messaging see aws.Config.CredentialsChainVerboseErrors  `

**Comment by jesse-gonzalez** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Fix Latest Issues found in Repo](https://trello.com/c/jFBT1fOI/117-fix-latest-issues-found-in-repo)
